# version format
version: v{build}

branches:
  only:
    - master
    - deployment

# Skipping commits with particular message or from specific user
skip_commits:
  message: "*[skip ci]*"

image: Visual Studio 2022

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  package_token:
    secure: oeB0vPa3ehegduJ/WnxLssnK6wiIc8MVx0lVYeiXKT6pIz9ZDQ4ioQ55g6GYz9dW

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

before_build:
  - ps: (Get-Content nuget.config).replace('Insert token here', $env:package_token) | Set-Content nuget.config
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln
  - nuget install GitCommitId -DependencyVersion Highest -OutputDirectory packages

configuration:
  - Release
  - Debug

build:
  project: $(APPVEYOR_PROJECT_NAME).sln

after_build:
  - ps: |-
        $xml = [xml](Get-Content .\Analyzer\Analyzer.csproj)
  - ps: $version = $xml.Project.PropertyGroup.Version
  - ps: set version_tag v$version
  - ps: $version_tag = $version_tag.Trim()
  - ps: $env:VERSION_TAG = $version_tag
  - echo Version is "%VERSION_TAG%"

test: off

artifacts:
  - path: Package\bin\Debug\$(APPVEYOR_PROJECT_NAME).*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    type: NuGetPackage
  - path: Package\bin\Release\$(APPVEYOR_PROJECT_NAME).*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Release
    type: NuGetPackage

deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    symbol_server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    username: dlebansais
    api_key:
      secure: P1otXPxREK8T2L9vw4vpvvpXYlMyCTGa/iQIfuXtr4mjOFZBYR83Aie3hTZotfOu
    on:
      branch: deployment
      configuration: Debug
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    skip_symbols: true
    username: dlebansais
    api_key:
      secure: P1otXPxREK8T2L9vw4vpvvpXYlMyCTGa/iQIfuXtr4mjOFZBYR83Aie3hTZotfOu
    on:
      branch: deployment
      configuration: Release
