//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsistencyAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsistencyAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent const-ness of unmodified variable.
        /// </summary>
        public static string ConA1000Description {
            get {
                return ResourceManager.GetString("ConA1000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can be made constant.
        /// </summary>
        public static string ConA1000MessageFormat {
            get {
                return ResourceManager.GetString("ConA1000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable can be made constant.
        /// </summary>
        public static string ConA1000Title {
            get {
                return ResourceManager.GetString("ConA1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for namespaces.
        /// </summary>
        public static string ConA1300Description {
            get {
                return ResourceManager.GetString("ConA1300Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad namespace name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1300MessageFormat {
            get {
                return ResourceManager.GetString("ConA1300MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace names must be consistent.
        /// </summary>
        public static string ConA1300Title {
            get {
                return ResourceManager.GetString("ConA1300Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for classes.
        /// </summary>
        public static string ConA1301Description {
            get {
                return ResourceManager.GetString("ConA1301Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad class name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1301MessageFormat {
            get {
                return ResourceManager.GetString("ConA1301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class names must be consistent.
        /// </summary>
        public static string ConA1301Title {
            get {
                return ResourceManager.GetString("ConA1301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for records.
        /// </summary>
        public static string ConA1302Description {
            get {
                return ResourceManager.GetString("ConA1302Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad record name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1302MessageFormat {
            get {
                return ResourceManager.GetString("ConA1302MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record names must be consistent.
        /// </summary>
        public static string ConA1302Title {
            get {
                return ResourceManager.GetString("ConA1302Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for structs.
        /// </summary>
        public static string ConA1303Description {
            get {
                return ResourceManager.GetString("ConA1303Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad struct name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1303MessageFormat {
            get {
                return ResourceManager.GetString("ConA1303MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct names must be consistent.
        /// </summary>
        public static string ConA1303Title {
            get {
                return ResourceManager.GetString("ConA1303Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for enums.
        /// </summary>
        public static string ConA1304Description {
            get {
                return ResourceManager.GetString("ConA1304Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad enum name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1304MessageFormat {
            get {
                return ResourceManager.GetString("ConA1304MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum names must be consistent.
        /// </summary>
        public static string ConA1304Title {
            get {
                return ResourceManager.GetString("ConA1304Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for interfaces.
        /// </summary>
        public static string ConA1305Description {
            get {
                return ResourceManager.GetString("ConA1305Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad interface name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1305MessageFormat {
            get {
                return ResourceManager.GetString("ConA1305MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface names must be consistent.
        /// </summary>
        public static string ConA1305Title {
            get {
                return ResourceManager.GetString("ConA1305Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for enum members.
        /// </summary>
        public static string ConA1306Description {
            get {
                return ResourceManager.GetString("ConA1306Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad enum member name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1306MessageFormat {
            get {
                return ResourceManager.GetString("ConA1306MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum member names must be consistent.
        /// </summary>
        public static string ConA1306Title {
            get {
                return ResourceManager.GetString("ConA1306Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for delegates.
        /// </summary>
        public static string ConA1307Description {
            get {
                return ResourceManager.GetString("ConA1307Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad delegate name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1307MessageFormat {
            get {
                return ResourceManager.GetString("ConA1307MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate names must be consistent.
        /// </summary>
        public static string ConA1307Title {
            get {
                return ResourceManager.GetString("ConA1307Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for events.
        /// </summary>
        public static string ConA1308Description {
            get {
                return ResourceManager.GetString("ConA1308Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad event name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1308MessageFormat {
            get {
                return ResourceManager.GetString("ConA1308MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event names must be consistent.
        /// </summary>
        public static string ConA1308Title {
            get {
                return ResourceManager.GetString("ConA1308Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for fields.
        /// </summary>
        public static string ConA1309Description {
            get {
                return ResourceManager.GetString("ConA1309Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad field name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1309MessageFormat {
            get {
                return ResourceManager.GetString("ConA1309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names must be consistent.
        /// </summary>
        public static string ConA1309Title {
            get {
                return ResourceManager.GetString("ConA1309Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for properties.
        /// </summary>
        public static string ConA1310Description {
            get {
                return ResourceManager.GetString("ConA1310Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad property name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1310MessageFormat {
            get {
                return ResourceManager.GetString("ConA1310MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property names must be consistent.
        /// </summary>
        public static string ConA1310Title {
            get {
                return ResourceManager.GetString("ConA1310Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for methods.
        /// </summary>
        public static string ConA1311Description {
            get {
                return ResourceManager.GetString("ConA1311Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad method name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1311MessageFormat {
            get {
                return ResourceManager.GetString("ConA1311MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method names must be consistent.
        /// </summary>
        public static string ConA1311Title {
            get {
                return ResourceManager.GetString("ConA1311Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a consistent naming scheme for parameters.
        /// </summary>
        public static string ConA1312Description {
            get {
                return ResourceManager.GetString("ConA1312Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameter name &apos;{0}&apos; .
        /// </summary>
        public static string ConA1312MessageFormat {
            get {
                return ResourceManager.GetString("ConA1312MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter names must be consistent.
        /// </summary>
        public static string ConA1312Title {
            get {
                return ResourceManager.GetString("ConA1312Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent documentation of enumeration element.
        /// </summary>
        public static string ConA1602Description {
            get {
                return ResourceManager.GetString("ConA1602Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can be documented.
        /// </summary>
        public static string ConA1602MessageFormat {
            get {
                return ResourceManager.GetString("ConA1602MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration element can be documented.
        /// </summary>
        public static string ConA1602Title {
            get {
                return ResourceManager.GetString("ConA1602Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regions for all class code or not at all.
        /// </summary>
        public static string ConA1700Description {
            get {
                return ResourceManager.GetString("ConA1700Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is missing regions.
        /// </summary>
        public static string ConA1700MessageFormat {
            get {
                return ResourceManager.GetString("ConA1700MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is missing regions.
        /// </summary>
        public static string ConA1700Title {
            get {
                return ResourceManager.GetString("ConA1700Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid nested regions and refactor the code or use partial classes instead.
        /// </summary>
        public static string ConA1701Description {
            get {
                return ResourceManager.GetString("ConA1701Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region &apos;{0}&apos; is nested within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1701MessageFormat {
            get {
                return ResourceManager.GetString("ConA1701MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use nested regions.
        /// </summary>
        public static string ConA1701Title {
            get {
                return ResourceManager.GetString("ConA1701Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public member of a class is not the same region as other public members.
        /// </summary>
        public static string ConA1702Description {
            get {
                return ResourceManager.GetString("ConA1702Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class member &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1702MessageFormat {
            get {
                return ResourceManager.GetString("ConA1702MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public member outside the expected region.
        /// </summary>
        public static string ConA1702Title {
            get {
                return ResourceManager.GetString("ConA1702Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protected member of a class is not the same region as other protected members.
        /// </summary>
        public static string ConA1703Description {
            get {
                return ResourceManager.GetString("ConA1703Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class member &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1703MessageFormat {
            get {
                return ResourceManager.GetString("ConA1703MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected member outside the expected region.
        /// </summary>
        public static string ConA1703Title {
            get {
                return ResourceManager.GetString("ConA1703Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public constructor of a class is not the same region as other public constructors.
        /// </summary>
        public static string ConA1704Description {
            get {
                return ResourceManager.GetString("ConA1704Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class constructor &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1704MessageFormat {
            get {
                return ResourceManager.GetString("ConA1704MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public constructor outside the expected region.
        /// </summary>
        public static string ConA1704Title {
            get {
                return ResourceManager.GetString("ConA1704Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public field of a class is not the same region as other public fields.
        /// </summary>
        public static string ConA1705Description {
            get {
                return ResourceManager.GetString("ConA1705Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1705MessageFormat {
            get {
                return ResourceManager.GetString("ConA1705MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public field outside the expected region.
        /// </summary>
        public static string ConA1705Title {
            get {
                return ResourceManager.GetString("ConA1705Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public method of a class is not the same region as other public methods.
        /// </summary>
        public static string ConA1706Description {
            get {
                return ResourceManager.GetString("ConA1706Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1706MessageFormat {
            get {
                return ResourceManager.GetString("ConA1706MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public method outside the expected region.
        /// </summary>
        public static string ConA1706Title {
            get {
                return ResourceManager.GetString("ConA1706Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public property of a class is not the same region as other public properties.
        /// </summary>
        public static string ConA1707Description {
            get {
                return ResourceManager.GetString("ConA1707Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not within region &apos;{1}&apos;.
        /// </summary>
        public static string ConA1707MessageFormat {
            get {
                return ResourceManager.GetString("ConA1707MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public property outside the expected region.
        /// </summary>
        public static string ConA1707Title {
            get {
                return ResourceManager.GetString("ConA1707Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A region is started within some block but ends in another block at a different block level.
        /// </summary>
        public static string ConA1708Description {
            get {
                return ResourceManager.GetString("ConA1708Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region &apos;{0}&apos; does not start and end at the same block level.
        /// </summary>
        public static string ConA1708MessageFormat {
            get {
                return ResourceManager.GetString("ConA1708MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end regions at the same block level.
        /// </summary>
        public static string ConA1708Title {
            get {
                return ResourceManager.GetString("ConA1708Title", resourceCulture);
            }
        }
    }
}
